# Generated by Django 5.2.17 on 2026-10-04 21:40

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('conejo', 'Conejo'), ('ave', 'Ave')], max_length=20, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('estado_salud', models.CharField(choices=[('saludable', 'Saludable'), ('lesionado', 'Lesionado'), ('enfermo', 'Enfermo'), ('desnutrido', 'Desnutrido')], max_length=20, verbose_name='Estado de salud')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('foto', models.FileField(blank=True, null=True, upload_to='animales/', verbose_name='Foto')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
